apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: budget-app-run
spec:
  pipelineRef:
    name: budget-app-pipeline
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
  params:
    - name: repo-url
      value: https://github.com/Ajinkyapatil1234/Budget-App.git
    - name: image-url
      value: docker.io/ajinkyadoc1234/budget-app:latest
  taskRunSpecs:
    - pipelineTaskName: kaniko-build
      serviceAccountName: dockerhub-serviceaccount
