apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko
spec:
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
    - name: CONTEXT
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /kaniko/.docker/config.json
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=$(params.DOCKERFILE)"
        - "--context=$(workspaces.source.path)/$(params.CONTEXT)"
        - "--destination=$(params.IMAGE)"
        - "--verbosity=info"
        - "--skip-tls-verify"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret

 
                                              
